### ISSUE TITLE
Venue 1: Keck Kiosk

### ISSUE THREAD

**Issue by az3ta** [squatted-online/squatted-online.github.io#8]
### Info
**Name:** Keck Kiosk
**Address:** Klybeckstrasse 1c, 4057 Basel, [G Maps](https://goo.gl/maps/hQ1XyigbvAhHGe2g7)
**Website:** https://www.keck-kiosk.ch
**Period:** 1st February – 1st March

### Description
A small kiosk in the center of Basel; is located at the edge of a square shared by bars, restaurants and three cultural centers. The kiosk has a big window of 343 x 132 cm and an inside space of 90 cm depth, 250 cm height and 400 cm length.
There is electricity and a sound system (sound is allowed only until 10 PM).
The window has a shutter that opens automatically and can be programmed.
Is possible to access the space at any time of the day, inside there is a shelf and a small fridge.
At the right side (if looking at it) there is a backlit frame for one poster.

### Use
This will be the main venue of the embassy and it will be open for its entire duration.
_The Squatted_ website will be displayed here.
Artist can use the space for any activity they want, including: reorganising the (small) space, deciding for opening and closing times, do performances, etc.

### Attachement
Keck Kiosk manual with all the information. Unfortunately only in German.

[Keck_Handbuch_2-1.pdf](https://github.com/squatted-online/squatted-online.github.io/files/3618297/Keck_Handbuch_2-1.pdf)

**Comment by pi43r** [comment]
Some years ago I was planning a performance for such a kiosk in Weimar. Unfortunately it never happened, but maybe now is a good time for a revival :) 

I would like to squat the kiosk for a week. Passers will be able to see whatever I am doing on my Laptop or phone through screens/projectors. While there I will keep working on whatever I have to do and create small site specific works. 
What do you think? 
Is it feasible to stay there for some time? 
Do you have internet? (Otherwise an LTE router is not super expensive)
A toilet that is closeby? (preferably open during the night, too)
It might be very cold in March, but with a heater it should be ok, right?

**Comment by Yyyyaaaannnnoooo** [comment]
Hi there

I think the idea is great!
There is no interbet at the kiosk, we could try to provide you a 4G router. There is a public toilet nearby, but during the day you may use the one of kabar close by. it might be cold but we can look for a little heater to keep you warm.
Let us know about your plans.

**Comment by az3ta** [comment]
Ciao @pi43r ! 
I also think the idea is super. Do you have something you prepared for the performance in Weimar? If yes would be cool if you share it here!

As @Yyyyaaaannnnoooo already said there is no problem for the organization issues, but let's start to keep track of them so we can organize everything better.

Please note that we changed the dates of the event: it will happen in February for the all month.
